spring.application.name=task-scheduler
client.url=http://localhost:8080
spring.data.mongodb.uri=mongodb://localhost:27017/scheduler_db
server.port=8081
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG